name: Book

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: |
          python -m pip install poetry
      - name: Export Requirements
        run: |
          poetry export --without-hashes --extras all --dev -f requirements.txt --output dev-requirements.txt
          pip install -r dev-requirements.txt
      - name: Build Book
        run: |
          jupyter-book build book/ --builder=dirhtml
      - name: Deploy Book
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/dirhtml
